name: stagexl_ui_components
description: A set of lightwieght UI components and mixins for StageXL.

version: 0.0.1
author: Mark Tanner <admin@64bitdragon.com>
homepage: https://github.com/marktanner1331/stagexl_ui_components

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  stagexl: ^1.1.0
